name: CD 파이프라인

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: SSH 키 설정
        run: |
         echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
         chmod 600 key.pem

      - name: 애플리케이션 파일 전송
          run: |
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
          --exclude='.git/' \
          --exclude='node_modules/' \
          --exclude='db.sqlite3' \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app/

      - name: EC2에서 애플리케이션 배포
          run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
          cd ~/app
          docker compose down
          docker compose build
          docker compose up -d
          ENDSSH

      - name: SSH 키 삭제
        if: always()
        run: rm -f key.pem
